# Name of loaded config, to show to user
name = "Block Device Manager (with FHI)"

# Modules to load in load environment
[[module-le]]
file = "bdm.irx"
# These 3 drivers are needed for isofs
# it would be nice if we could remove that dependency
[[module-le]]
file = "iomanX.irx"
[[module-le]]
file = "fileXio.irx"
[[module-le]]
file = "isofs.irx"

# Modules to load in emulation environment
# the end result of these drivers (in combination with the BDM BD drivers) must
# result in the file handle interface (fhi) to be available to the emulation
# environment
[[module-ee]]
file = "fhi_bdm.irx"
ioprp = "FHI" # ID used by loader
