# Name of loaded config, to show to user
name = "ATA via DEV9 BDM driver"

# Drivers this driver depends on (config file must exist)
depends = "bdm"

# Modules to load
[[module]]
file = "dev9_ns.irx" # no-shutdown version, to prevent games shutting down the dev9
[[module]]
file = "ata_bd.irx"

# Modules of the game that are faked/blocked
[[fake]]
file = "DEV9.IRX"
name = "dev9"
version = 0x0208
startrv = 0 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
[[fake]]
file = "ATAD.IRX"
name = "atad_driver"
version = 0x0207
startrv = 0 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
