# Name of loaded config, to show to user
name = "UDPBD - UDP Block Device BDM driver"

# Drivers this driver depends on (config file must exist)
depends = "bdm"

# Modules to load
[[module]]
file = "dev9_hidden.irx" # hidden version to hide from the game
[[module]]
file = "smap_udpbd.irx"
args = ["ip=192.168.1.10"]

# Faking strategy
# ---------------
# To prevent games from trying to use networing:
# - dev9 is not resident (startrv 1) becouse it does not detect dev9 hardware
# - all modules depending on dev9 fail to load becouse dev9 is not resident
[[fake]]
file = "DEV9.IRX"
name = "dev9"
version = 0x0208
loadrv = 0 # 0=ok, -xxx=error code (module not loaded)
startrv = 1 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
[[fake]]
file = "ENT_SMAP.IRX"
name = "ent_smap"
version = 0x021f
loadrv = -200 # KE_LINKERR becouse dev9 does not exist
startrv = 1    # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
[[fake]]
file = "SMAP.IRX"
name = "INET_SMAP_driver"
version = 0x0219
loadrv = -200 # KE_LINKERR becouse dev9 does not exist
startrv = 1    # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
