# Name of device driver, to show to user
name = "ATA via DEV9 BDM driver"

# Type of device driver, support for this type must exist in
# type-<type>-load.toml   for the load   environment
# type-<type>-ingame.toml for the ingame environment
type = "bdm"

# Device mode as used by the EECORE (used for patches), support for this type must exist in the EECORE
mode = "BDM_ATA_MODE"

# Modules to load
[[module]]
file = "ps2dev9.irx"
[[module]]
file = "ata_bd.irx"

# Modules of the game that are faked/blocked
[[fake]]
file = "DEV9.IRX"
name = "dev9"
replace = true
version = 0x0208
return = 0 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
[[fake]]
file = "ATAD.IRX"
name = "atad_driver"
replace = true
version = 0x0207
return = 0 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
