# Name of device driver, to show to user
name = "Builtin DVD drive with original disk"

# Type of device driver, support for this type must exist in
# type-<type>-load.toml   for the load   environment
# type-<type>-ingame.toml for the ingame environment
type = "dvd"

# Device mode as used by the EECORE (used for patches), support for this type must exist in the EECORE
mode = "-"
