# Name of device driver, to show to user
name = "UDPBD - UDP Block Device BDM driver"

# Type of device driver, support for this type must exist in
# type-<type>-load.toml   for the load   environment
# type-<type>-ingame.toml for the ingame environment
type = "bdm"

# Device mode as used by the EECORE (used for patches), support for this type must exist in the EECORE
mode = "BDM_UDP_MODE"

# Modules to load
[[module]]
file = "ps2dev9.irx"
[[module]]
file = "smap.irx"
args = "ip=192.168.1.10"

# Modules of the game that are faked/blocked
[[fake]]
file = "DEV9.IRX"
name = "dev9"
replace = true
version = 0x0208
return = 0 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
[[fake]]
file = "SMAP.IRX"
name = "INET_SMAP_driver"
replace = false
version = 0x0219
return = 2 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
[[fake]]
file = "ENT_SMAP.IRX"
name = "ent_smap"
replace = false
version = 0x021f
return = 2 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
