# Name of device driver, to show to user
name = "MX4SIO in MC2 BDM driver"

# Type of device driver, support for this type must exist in
# type-<type>-load.toml   for the load   environment
# type-<type>-ingame.toml for the ingame environment
type = "bdm"

# Device mode as used by the EECORE (used for patches), support for this type must exist in the EECORE
mode = "BDM_M4S_MODE"

# Modules to load
[[module]]
file = "mx4sio_bd_mini.irx"
