# Name of loaded config, to show to user
name = "CD/DVD emulation using image file"

# Modules to load
[[module-emu]]
file = "cdvdman_emu.irx"
ioprp = "CDVDMAN"
[[module-emu]]
file = "cdvdfsv.irx"
ioprp = "CDVDFSV"

# Modules of the game that are faked/blocked
[[fake]]
file = "CDVDFSV.IRX"
name = "cdvd_ee_driver"
replace = true
#unload = true // FIXME this is broken, can be tested with Jak X
version = 0x0202
startrv = 2 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
[[fake]]
file = "CDVDSTM.IRX"
name = "cdvd_st_driver"
replace = false
version = 0x0202
startrv = 2 # 0=RESIDENT_END, 1=NO_RESIDENT_END, 2=REMOVABLE_END
