# Name of loaded config, to show to user
name = "System settings and drivers"

# Override the 8-byte string returned by:
# - sceCdRI
# This string is also used by:
# - sceCdReadGUID
# - sceCdReadModelID
#
# This string is used (for instance) by the sony network configuration
# to verify if the config belongs to the specific console.
#
#ilink_id = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

# Use the 5-byte string returned by:
# - sceCdReadDiskID
#disk_id = [0x00, 0x00, 0x00, 0x00, 0x00]

# Modules to load in emulation environment
[[module-emu]]
file = "eesync.irx"
ioprp = "EESYNC"
[[module-emu]]
file = "imgdrv.irx"
[[module-emu]]
file = "fakemod.irx"
ioprp = "FAKEMOD" # ID used by loader
