#
# Configuration for BDM load environment
#

# Modules to load
[[module]]
file = "bdm.irx"
[[module]]
file = "bdmfs_fatfs.irx"

# These 3 drivers are needed for isofs
# it would be nice if we could remove that dependency
[[module]]
file = "iomanX.irx"
[[module]]
file = "fileXio.irx"
[[module]]
file = "isofs.irx"
